server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST:http://217.198.13.249:30096}/realms/geogreen
          jwk-set-uri: ${KEYCLOAK_HOST:http://217.198.13.249:30096}/realms/geogreen/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
#        geospatial-server
        - id: geospatial-server-api-docs
          uri: ${GEOSPATIAL_SERVER_HOST:http://217.198.13.249:30091}
          predicates:
            - Path=/geospatial-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: geospatial-server-urls
          uri: ${GEOSPATIAL_SERVER_HOST:http://217.198.13.249:30091}
          predicates:
            - Path=/geo/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        user-server
        - id: user-server-api-docs
          uri: ${USER_SERVER_HOST:http://217.198.13.249:30097}
          predicates:
            - Path=/user-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: user-server-urls
          uri: ${USER_SERVER_HOST:http://217.198.13.249:30097}
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        file-server
        - id: file-server-api-docs
          uri: ${FILE_SERVER_HOST:http://217.198.13.249:30092}
          predicates:
            - Path=/file-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: file-server-urls
          uri: ${FILE_SERVER_HOST:http://217.198.13.249:30092}
          predicates:
            - Path=/file/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        keycloak
        - id: keycloak
          uri: ${KEYCLOAK_HOST:http://217.198.13.249:30096}
          predicates:
            - Path=/realms/geogreen, /realms/geogreen/**, /realms/**, /admin/master/**, /auth/**, /realms/**, /admin/**, /auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        collect-user-data
        - id: collect-user-data-server-api-docs
          uri: ${COLLECT_USER_DATA_HOST:http://217.198.13.249:30095}
          predicates:
            - Path=/collect-user-data-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: collect-user-data-server-urls
          uri: ${COLLECT_USER_DATA_HOST:http://217.198.13.249:30095}
          predicates:
            - Path=/user-marker/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        event-manager-server
        - id: event-manager-server-api-docs
          uri: ${EVENT_MANAGER_SERVER_HOST:http://217.198.13.249:30094}
          predicates:
            - Path=/event-manager-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: event-manager-server-urls
          uri: ${EVENT_MANAGER_SERVER_HOST:http://217.198.13.249:30094}
          predicates:
            - Path=/event/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        photo-analyser-server
        - id: photo-analyser-server-api-docs
          uri: ${PHOTO_ANALYSER_SERVER_HOST:http://217.198.13.249:30093}
          predicates:
            - Path=/photo-analyser-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: photo-analyser-server-urls
          uri: ${PHOTO_ANALYSER_SERVER_HOST:http://217.198.13.249:30093}
          predicates:
            - Path=/analyse/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        notification-server
        - id: notification-server-api-docs
          uri: ${NOTIFICATION_SERVER_HOST:http://217.198.13.249:30098}
          predicates:
            - Path=/notification-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: notification-server-urls
          uri: ${NOTIFICATION_SERVER_HOST:http://217.198.13.249:30098}
          predicates:
            - Path=/notification/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
#        report-server
        - id: report-server-api-docs
          uri: ${REPORT_SERVER_HOST:http://217.198.13.249:30089}
          predicates:
            - Path=/report-server/v3/api-docs
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback
        - id: report-server-urls
          uri: ${REPORT_SERVER_HOST:http://217.198.13.249:30089}
          predicates:
            - Path=/report/**
          filters:
            - name: CircuitBreaker
              args:
                name: default-circuit-breaker
                fallbackUri: forward:/fallback

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: geospatial-server
        url: /geospatial-server/v3/api-docs
      - name: user-server
        url: /user-server/v3/api-docs
      - name: file-server
        url: /file-server/v3/api-docs
      - name: collect-user-data-server
        url: /collect-user-data-server/v3/api-docs
      - name: event-manager-server
        url: /event-manager-server/v3/api-docs
      - name: photo-analyser-server
        url: /photo-analyser-server/v3/api-docs
      - name: notification-server
        url: /notification-server/v3/api-docs
      - name: report-server
        url: /report-server/v3/api-docs

logging:
  level:
    root: ${LOG_LEVEL:info}
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:info}

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 300s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
    instances:
      default-circuit-breaker:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      default-circuit-breaker:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true