server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://217.198.13.249:30096}/realms/geogreen
          jwk-set-uri: ${KEYCLOAK_URL:http://217.198.13.249:30096}/realms/geogreen/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
#        geospatial-server
        - id: geospatial-server-api-docs
          uri: http://217.198.13.249:30091
          predicates:
            - Path=/geospatial-server/v3/api-docs
          filters:
            - StripPrefix=1
        - id: geospatial-server-urls
          uri: http://217.198.13.249:30091
          predicates:
            - Path=/geo/**
#        user-server
        - id: user-server-api-docs
          uri: http://217.198.13.249:30097
          predicates:
            - Path=/user-server/v3/api-docs
          filters:
            - StripPrefix=1
        - id: user-server-urls
          uri: http://217.198.13.249:30097
          predicates:
            - Path=/user/**
#        file-server
        - id: file-server-api-docs
          uri: http://217.198.13.249:30092
          predicates:
            - Path=/file-server/v3/api-docs
          filters:
            - StripPrefix=1
        - id: file-server-urls
          uri: http://217.198.13.249:30092
          predicates:
            - Path=/file/**
#        keycloak
        - id: file-server-urls
          uri: http://217.198.13.249:30096
          predicates:
            - Path=/realms/geogreen, /realms/geogreen/**
#        collect-user-data
        - id: collect-user-data-server-api-docs
          uri: http://217.198.13.249:30095
          predicates:
            - Path=/collect-user-data-server/v3/api-docs
          filters:
            - StripPrefix=1
        - id: collect-user-data-server-urls
          uri: http://217.198.13.249:30095
          predicates:
            - Path=/collect/**
#        event-manager-server
        - id: event-manager-server-api-docs
          uri: http://217.198.13.249:30094
          predicates:
            - Path=/event-manager-server/v3/api-docs
          filters:
            - StripPrefix=1
        - id: event-manager-server-urls
          uri: http://217.198.13.249:30094
          predicates:
            - Path=/event/**
#        photo-analyser-server
        - id: photo-analyser-server-api-docs
          uri: http://217.198.13.249:30093
          predicates:
            - Path=/photo-analyser-server/v3/api-docs
          filters:
            - StripPrefix=1
        - id: photo-analyser-server-urls
          uri: http://217.198.13.249:30093
          predicates:
            - Path=/analyse/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: geospatial-server
        url: /geospatial-server/v3/api-docs
      - name: user-server
        url: /user-server/v3/api-docs
      - name: file-server
        url: /file-server/v3/api-docs
      - name: collect-user-data-server
        url: /collect-user-data-server/v3/api-docs
      - name: event-manager-server
        url: /event-manager-server/v3/api-docs
      - name: photo-analyser-server
        url: /photo-analyser-server/v3/api-docs

#          filters:
#            - name: CircuitBreaker
#              args:
#                name: default-circuit-breaker
#                fallbackUri: forward:/fallback

logging:
  level:
    root: ${LOG_LEVEL:info}
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:info}

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        sliding-window-type: count_based
#        sliding-window-size: 10
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 60s
#        permitted-number-of-calls-in-half-open-state: 3
#        automatic-transition-from-open-to-half-open-enabled: true
#        minimum-number-of-calls: 3
#    instances:
#      default-circuit-breaker:
#        base-config: default
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 5s
#    instances:
#      default-circuit-breaker:
#        base-config: default